/** Complete utility classes for the camp UI; semantic hooks stay in templates. */
export const campStyles = {
  'camp-difficulty': ['tw:mb-6'].join(' '),
  'milestone-grid': [
    'tw:grid tw:[grid-template-columns:repeat(2,_minmax(0,_1fr))] tw:gap-5',
    'tw:[@media(max-width:_640px)]:[grid-template-columns:1fr]',
  ].join(' '),
  'milestone-card': [
    'tw:flex tw:flex-col tw:gap-4 tw:p-6 tw:bg-surface tw:border tw:border-solid tw:border-line tw:rounded-[18px] tw:min-w-0',
    'tw:[&.is-ready]:border-[#739f8d] tw:[&.is-ready]:[box-shadow:inset_0_0_0_1px_#739f8d]',
    'tw:[&.is-claimed]:bg-[#f1f4ef]',
    'tw:[&_h2]:text-[20px] tw:[&_h2]:[margin:4px_0]',
    'tw:[&_h3]:text-[16px] tw:[&_h3]:[margin:12px_0_8px]',
    'tw:[&_p]:m-0 tw:[&_p]:[line-height:1.7] tw:[&_p]:text-muted',
    'tw:[@media(max-width:_640px)]:p-4.5',
  ].join(' '),
  'milestone-heading': ['tw:flex tw:items-center tw:gap-4', 'tw:[&_img]:w-15 tw:[&_img]:h-15'].join(
    ' ',
  ),
  'milestone-progress': [
    'tw:flex tw:items-center tw:gap-3 tw:[font:13px_var(--mono)]',
    'tw:[&_progress]:w-full tw:[&_progress]:min-w-0 tw:[&_progress]:h-2 tw:[&_progress]:[accent-color:#3f8b72]',
    'tw:[&_span]:whitespace-nowrap',
  ].join(' '),
  'milestone-reward': [
    'tw:p-4 tw:rounded-xl tw:bg-[#f6f1e7] tw:[flex:1]',
    'tw:[&>strong]:text-[#8b662e] tw:[&>strong]:[font:600_18px_var(--mono)]',
  ].join(' '),
  'milestone-badge': [
    'tw:inline-block tw:text-[#286851] tw:bg-[#e3f0e8] tw:rounded-[20px] tw:[padding:3px_8px] tw:text-[12px]',
  ].join(' '),
  'camp-header': [
    'tw:flex tw:items-center tw:justify-between tw:gap-5 tw:mb-7',
    'tw:[&_h1]:mb-0',
    'tw:[@media(max-width:_620px)]:gap-3',
    'tw:[@media(max-width:_620px)]:[&_h1]:text-[28px]',
    'tw:[@media(max-width:_620px)]:[&_.eyebrow]:text-[9px] tw:[@media(max-width:_620px)]:[&_.eyebrow]:[letter-spacing:1px]',
  ].join(' '),
  'camp-wallet': [
    'tw:flex tw:items-center tw:justify-start tw:gap-3 tw:[padding:12px_18px] tw:border tw:border-solid tw:border-line tw:[border-radius:14px] tw:bg-surface',
    'tw:[&_.dungeon-sprite]:w-10 tw:[&_.dungeon-sprite]:h-10',
    'tw:[&_span]:block tw:[&_span]:text-muted tw:[&_span]:text-[12px]',
    'tw:[&_strong]:block tw:[&_strong]:[font:500_clamp(20px,_2vw,_28px)_var(--mono)]',
    'tw:[@media(max-width:_620px)]:p-2.5 tw:[@media(max-width:_620px)]:gap-1.5',
    'tw:[@media(max-width:_620px)]:[&_.dungeon-sprite]:w-7 tw:[@media(max-width:_620px)]:[&_.dungeon-sprite]:h-7',
    'tw:[@media(max-width:_620px)]:[&_strong]:text-[18px]',
  ].join(' '),
  'camp-summary-heading': [
    'tw:flex tw:items-center tw:justify-between tw:gap-5',
    'tw:[&_h3]:m-0 tw:[&_h3]:text-[14px] tw:[&_h3]:font-medium',
    'tw:[&>span]:text-muted tw:[&>span]:[font:13px_var(--mono)]',
  ].join(' '),
  'camp-route-summary': [
    'tw:flex tw:items-center tw:justify-between tw:gap-5 tw:mt-6 tw:py-4.5 tw:[border-top:1px_solid_var(--line)]',
    'tw:[&_span]:block tw:[&_span]:text-muted tw:[&_span]:text-[12px] tw:[&_span]:[margin-bottom:5px]',
    'tw:[&_strong]:text-[17px] tw:[&_strong]:font-medium',
    'tw:[&_p]:m-0 tw:[&_p]:text-right tw:[&_p]:text-muted tw:[&_p]:[font:12px/1.8_var(--mono)]',
  ].join(' '),
  'camp-back': ['tw:py-2 tw:px-0'].join(' '),
  'camp-overview': [
    'tw:grid tw:[grid-template-columns:1.2fr_1fr] tw:gap-6',
    'tw:[@media(max-width:_900px)]:gap-4',
    'tw:[@media(max-width:_620px)]:[grid-template-columns:minmax(0,_1fr)]',
  ].join(' '),
  'camp-departure': [
    'tw:border tw:border-solid tw:border-line tw:rounded-[20px] tw:[padding:clamp(20px,_2.5vw,_36px)] tw:bg-surface',
    'tw:[&>.primary-button]:w-full tw:[&>.primary-button]:mt-3',
  ].join(' '),
  'camp-current-profession': [
    'tw:flex tw:items-center tw:gap-6 tw:[margin:24px_0]',
    'tw:[&>.dungeon-sprite]:w-28 tw:[&>.dungeon-sprite]:h-28 tw:[&>.dungeon-sprite]:shrink-0',
    'tw:[&_span]:text-muted tw:[&_span]:text-[12px]',
    'tw:[&_h2]:text-[26px] tw:[&_h2]:[margin:4px_0_10px]',
    'tw:[&_p]:m-0 tw:[&_p]:text-muted tw:[&_p]:[line-height:1.7] tw:[&_p]:text-[14px]',
    'tw:[@media(max-width:_900px)]:gap-3.5',
    'tw:[@media(max-width:_900px)]:[&>.dungeon-sprite]:w-20 tw:[@media(max-width:_900px)]:[&>.dungeon-sprite]:h-20',
  ].join(' '),
  'camp-loadout-summary': [
    'tw:flex tw:flex-wrap tw:gap-2 tw:list-none tw:p-0 tw:[margin:14px_0_24px]',
    'tw:[&_li]:flex tw:[&_li]:items-center tw:[&_li]:[gap:7px] tw:[&_li]:border tw:[&_li]:border-solid tw:[&_li]:border-line tw:[&_li]:[padding:7px_10px] tw:[&_li]:[border-radius:10px] tw:[&_li]:text-[13px]',
    'tw:[&_.dungeon-sprite]:w-7 tw:[&_.dungeon-sprite]:h-7',
  ].join(' '),
  'camp-destinations': [
    'tw:grid tw:[grid-template-rows:repeat(4,_1fr)] tw:gap-3',
    'tw:[@media(max-width:_620px)]:[grid-template-columns:repeat(2,_minmax(0,_1fr))] tw:[@media(max-width:_620px)]:[grid-template-rows:auto]',
  ].join(' '),
  'camp-destination': [
    'tw:flex tw:items-center tw:gap-4.5 tw:border tw:border-solid tw:border-line tw:rounded-2xl tw:bg-surface tw:[padding:18px_22px] tw:text-left',
    'tw:[&:hover]:border-[var(--blue)]',
    'tw:[&>.dungeon-sprite]:w-14 tw:[&>.dungeon-sprite]:h-14 tw:[&>.dungeon-sprite]:shrink-0',
    'tw:[&>span:nth-child(2)]:[flex:1]',
    'tw:[&_strong]:block tw:[&_strong]:text-[17px] tw:[&_strong]:font-medium tw:[&_strong]:mb-1.5',
    'tw:[&_small]:block tw:[&_small]:text-muted tw:[&_small]:text-[13px] tw:[&_small]:[line-height:1.5]',
    'tw:[&>span:last-child]:text-muted',
    'tw:[@media(max-width:_900px)]:p-4 tw:[@media(max-width:_900px)]:gap-3',
    'tw:[@media(max-width:_900px)]:[&>.dungeon-sprite]:w-10.5 tw:[@media(max-width:_900px)]:[&>.dungeon-sprite]:h-10.5',
    'tw:[@media(max-width:_620px)]:items-start tw:[@media(max-width:_620px)]:flex-col',
    'tw:[@media(max-width:_620px)]:[&>span:last-child]:hidden',
    'tw:[@media(max-width:_620px)]:[&_strong]:text-[15px]',
    'tw:[@media(max-width:_620px)]:[&_small]:text-[12px]',
  ].join(' '),
  'camp-history-summary': ['tw:text-muted tw:text-[12px] tw:mt-5'].join(' '),
  'camp-subnav': [
    'tw:flex tw:gap-2 tw:flex-wrap tw:pb-5 tw:[border-bottom:1px_solid_var(--line)] tw:mb-7',
    'tw:[&_button]:[padding:10px_14px] tw:[&_button]:min-h-11 tw:[&_button]:[border-radius:9px] tw:[&_button]:border tw:[&_button]:border-solid tw:[&_button]:border-transparent tw:[&_button]:text-[13px]',
    'tw:[&_[aria-current=page]]:text-[var(--blue)] tw:[&_[aria-current=page]]:bg-surface tw:[&_[aria-current=page]]:border-line',
    'tw:[&_button:hover]:text-[var(--blue)]',
    'tw:[@media(max-width:_620px)]:gap-1',
    'tw:[@media(max-width:_620px)]:[&_button]:[padding:9px_10px] tw:[@media(max-width:_620px)]:[&_button]:text-[12px]',
  ].join(' '),
  'shop-filters': [
    'tw:flex tw:gap-2 tw:flex-wrap tw:[margin:20px_0]',
    'tw:[&_button]:[padding:10px_14px] tw:[&_button]:min-h-11 tw:[&_button]:[border-radius:9px] tw:[&_button]:border tw:[&_button]:border-solid tw:[&_button]:border-transparent tw:[&_button]:text-[13px]',
    'tw:[&_[aria-pressed=true]]:text-[var(--blue)] tw:[&_[aria-pressed=true]]:bg-surface tw:[&_[aria-pressed=true]]:border-line',
    'tw:[&_button:hover]:text-[var(--blue)]',
    'tw:[@media(max-width:_620px)]:gap-1',
    'tw:[@media(max-width:_620px)]:[&_button]:[padding:9px_10px] tw:[@media(max-width:_620px)]:[&_button]:text-[12px]',
  ].join(' '),
  'camp-budget': [
    'tw:flex tw:gap-4 tw:items-baseline tw:text-muted tw:text-[14px]',
    'tw:[&_strong]:text-ink tw:[&_strong]:[font:22px_var(--mono)]',
  ].join(' '),
  'camp-locked': [
    'tw:max-w-130 tw:[margin:40px_auto] tw:text-center tw:[line-height:1.8]',
    'tw:[&>.dungeon-sprite]:w-24 tw:[&>.dungeon-sprite]:h-24',
    'tw:[&_p]:text-muted',
    'tw:[&_.primary-button]:mt-4',
  ].join(' '),
  'camp-professions': ['tw:[&_.dungeon-sprite]:w-18 tw:[&_.dungeon-sprite]:h-18'].join(' '),
  'shop-grid': [
    'tw:grid tw:[grid-template-columns:repeat(6,_minmax(0,_1fr))_minmax(280px,_2fr)] tw:gap-3 tw:[align-items:start]',
    'tw:[@media(min-width:_901px)_and_(max-width:_1200px)]:[grid-template-columns:repeat(4,_minmax(0,_1fr))_minmax(280px,_2fr)]',
    'tw:[@media(max-width:_900px)]:[grid-template-columns:repeat(3,_minmax(0,_1fr))]',
    'tw:[@media(max-width:_620px)]:gap-2',
  ].join(' '),
  'shop-tile': [
    'tw:[grid-column:var(--tile-column)] tw:[grid-row:var(--tile-row)] tw:relative tw:[aspect-ratio:1] tw:min-w-0 tw:w-full tw:grid tw:[grid-template-rows:minmax(0,_1fr)_auto_auto] tw:justify-items-center tw:items-center tw:[gap:5px] tw:[padding:12px_8px] tw:border tw:border-solid tw:border-line tw:rounded-xl tw:bg-surface tw:text-center',
    'tw:[&:hover]:border-[var(--blue)]',
    'tw:[&[aria-pressed=true]]:border-[var(--blue)] tw:[&[aria-pressed=true]]:[box-shadow:inset_0_0_0_1px_var(--blue)] tw:[&[aria-pressed=true]]:bg-[color-mix(in_srgb,_var(--blue)_4%,_var(--surface))]',
    'tw:[&_.dungeon-sprite]:[width:clamp(36px,_5.5vw,_76px)] tw:[&_.dungeon-sprite]:h-auto tw:[&_.dungeon-sprite]:max-h-full tw:[&_.dungeon-sprite]:object-contain',
    'tw:[&_strong]:text-[12px] tw:[&_strong]:font-medium tw:[&_strong]:[line-height:1.35] tw:[&_strong]:[overflow-wrap:anywhere]',
    'tw:[@media(min-width:_901px)_and_(max-width:_1200px)]:[grid-column:var(--compact-column)] tw:[@media(min-width:_901px)_and_(max-width:_1200px)]:[grid-row:var(--compact-row)]',
    'tw:[@media(max-width:_900px)]:[grid-column:var(--mobile-column)] tw:[@media(max-width:_900px)]:[grid-row:var(--mobile-row)]',
    'tw:[@media(max-width:_900px)]:[&_.dungeon-sprite]:[width:clamp(36px,_13vw,_100px)]',
    'tw:[@media(max-width:_620px)]:[padding:7px_5px] tw:[@media(max-width:_620px)]:[gap:3px]',
    'tw:[@media(max-width:_620px)]:[&_strong]:text-[11px]',
  ].join(' '),
  'shop-price': [
    'tw:text-muted tw:[font:12px_var(--mono)]',
    'tw:[@media(max-width:_620px)]:text-[11px]',
  ].join(' '),
  'shop-owned': ['tw:absolute tw:top-1.5 tw:[right:9px] tw:text-[var(--blue)] tw:text-[13px]'].join(
    ' ',
  ),
  'shop-detail': [
    'tw:[grid-column:7] tw:[grid-row:1_/_span_var(--shop-rows)] tw:sticky tw:top-5 tw:min-w-0 tw:[max-height:calc(100dvh_-_40px)] tw:overflow-y-auto tw:p-6 tw:ml-2 tw:border tw:border-solid tw:border-line tw:rounded-2xl tw:bg-surface tw:[scrollbar-width:thin]',
    'tw:[&>.dungeon-sprite]:block tw:[&>.dungeon-sprite]:w-22 tw:[&>.dungeon-sprite]:h-22 tw:[&>.dungeon-sprite]:[margin:20px_0_16px]',
    'tw:[&_h2]:[margin:0_0_12px] tw:[&_h2]:text-[22px]',
    'tw:[&_.profession-preview]:[padding:14px_0] tw:[&_.profession-preview]:[border-top:1px_solid_var(--line)]',
    'tw:[&_.profession-preview>img]:w-10 tw:[&_.profession-preview>img]:h-10',
    'tw:[&_.profession-preview_small]:hidden',
    'tw:[@media(min-width:_901px)_and_(max-width:_1200px)]:[grid-column:5] tw:[@media(min-width:_901px)_and_(max-width:_1200px)]:[grid-row:1_/_span_var(--compact-rows)]',
    'tw:[@media(max-width:_900px)]:[grid-column:1_/_-1] tw:[@media(max-width:_900px)]:[grid-row:var(--detail-row)] tw:[@media(max-width:_900px)]:static tw:[@media(max-width:_900px)]:m-0 tw:[@media(max-width:_900px)]:max-h-none tw:[@media(max-width:_900px)]:overflow-visible',
    'tw:[@media(max-width:_620px)]:p-5',
  ].join(' '),
  'shop-effect': ['tw:text-muted tw:text-[14px] tw:[line-height:1.85]'].join(' '),
  'shop-purchase': [
    'tw:pt-5 tw:mt-5 tw:[border-top:1px_solid_var(--line)]',
    'tw:[&_p]:text-muted tw:[&_p]:text-[12px]',
    'tw:[&_strong]:[font:24px_var(--mono)] tw:[&_strong]:text-ink tw:[&_strong]:mr-1.5',
    'tw:[&_button]:w-full',
  ].join(' '),
  'shop-purchase-status': [
    'tw:mb-0 tw:min-h-5 tw:text-[12px] tw:text-muted tw:[line-height:1.6]',
  ].join(' '),
}
