/** Shared gameplay utility groups; keep complete classes visible to the Tailwind scanner. */
export const gameplayStyles = {
  'expedition-dialog': [
    'tw:[&_h2:focus]:[outline:none]',
    'tw:[&.relic-dialog]:[width:min(820px,_calc(100vw_-_28px))] tw:[&.relic-dialog]:[overscroll-behavior:contain]',
    'tw:[&.relic-dialog]:[&_.choice-grid]:[grid-template-columns:repeat(auto-fit,_minmax(min(190px,_100%),_1fr))] tw:[&.relic-dialog]:[&_.choice-grid]:mb-0',
    'tw:[&.relic-dialog]:[&_.choice-grid:has(>:nth-child(4))]:[grid-template-columns:repeat(2,_minmax(0,_1fr))]',
    'tw:[&.relic-dialog]:[&_.choice-card]:items-center tw:[&.relic-dialog]:[&_.choice-card]:text-center',
    'tw:[&.relic-dialog]:[&_.choice-card_.dungeon-sprite]:w-22 tw:[&.relic-dialog]:[&_.choice-card_.dungeon-sprite]:h-22 tw:[&.relic-dialog]:[&_.choice-card_.dungeon-sprite]:[margin:0_auto_8px]',
    'tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-grid]:[grid-template-columns:minmax(0,_1fr)]',
    'tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-grid:has(>:nth-child(4))]:[grid-template-columns:minmax(0,_1fr)]',
    'tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card]:grid tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card]:[grid-template-columns:56px_minmax(0,_1fr)] tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card]:text-left tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card]:[gap:6px_12px] tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card]:p-4',
    'tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card_.dungeon-sprite]:w-14 tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card_.dungeon-sprite]:h-14 tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card_.dungeon-sprite]:[grid-row:span_2] tw:[&.relic-dialog]:[@media(max-width:_520px)]:[&_.choice-card_.dungeon-sprite]:m-0',
    'tw:[&.expedition-result-dialog]:[overscroll-behavior:contain]',
    'tw:[&.expedition-result-dialog]:[&>.primary-button]:w-full',
  ].join(' '),
  'settlement-total': [
    'tw:grid tw:justify-items-center tw:gap-3 tw:[margin:28px_0]',
    'tw:[&_.dungeon-sprite]:w-24 tw:[&_.dungeon-sprite]:h-24',
    'tw:[&_span]:text-muted',
    'tw:[&_strong]:text-[var(--blue)] tw:[&_strong]:[font:600_40px_var(--mono)]',
  ].join(' '),
  'relic-trigger': [
    'tw:inline-block tw:[width:fit-content] tw:mt-1.5 tw:[padding:3px_8px] tw:[border-radius:6px] tw:text-[var(--blue)] tw:bg-[#eef2ff]',
  ].join(' '),
  'relic-list': [
    'tw:[&_.dungeon-sprite]:w-8 tw:[&_.dungeon-sprite]:h-8 tw:[&_.dungeon-sprite]:mb-1.5',
    'tw:list-none tw:p-0 tw:flex tw:flex-col tw:gap-3',
    'tw:[&_li]:flex tw:[&_li]:flex-col tw:[&_li]:gap-1.5 tw:[&_li]:text-[13px]',
    'tw:[&_span]:text-muted tw:[&_span]:[line-height:1.6] tw:[&_span]:text-[12px]',
  ].join(' '),
  'run-sidebar': [
    'tw:px-0 tw:[padding-block:calc(8_*_var(--play-unit))]',
    'tw:[&_h3]:text-[calc(14_*_var(--play-unit))] tw:[&_h3]:[margin:26px_0_12px]',
    'tw:[&_.relic-menu_.relic-list]:grid tw:[&_.relic-menu_.relic-list]:[grid-template-columns:1fr] tw:[&_.relic-menu_.relic-list]:[padding:0_14px_14px] tw:[&_.relic-menu_.relic-list]:m-0 tw:[&_.relic-menu_.relic-list]:gap-2',
    'tw:[&_.relic-menu_.relic-list_li]:grid tw:[&_.relic-menu_.relic-list_li]:[grid-template-columns:38px_1fr] tw:[&_.relic-menu_.relic-list_li]:[gap:3px_9px] tw:[&_.relic-menu_.relic-list_li]:[align-items:start] tw:[&_.relic-menu_.relic-list_li]:[padding:12px_8px] tw:[&_.relic-menu_.relic-list_li]:[border-top:1px_solid_#e2e6da] tw:[&_.relic-menu_.relic-list_li]:bg-none tw:[&_.relic-menu_.relic-list_li]:[border-radius:0] tw:[&_.relic-menu_.relic-list_li]:text-left',
    'tw:[&_.relic-menu_.relic-list_li>img]:[grid-column:1] tw:[&_.relic-menu_.relic-list_li>img]:[grid-row:1_/_4] tw:[&_.relic-menu_.relic-list_li>img]:w-9 tw:[&_.relic-menu_.relic-list_li>img]:h-9',
    'tw:[&_.relic-menu_.relic-list_li>strong]:[grid-column:2] tw:[&_.relic-menu_.relic-list_li>strong]:block tw:[&_.relic-menu_.relic-list_li>strong]:text-[12px]',
    'tw:[&_.relic-menu_.relic-list_li>span]:[grid-column:2] tw:[&_.relic-menu_.relic-list_li>span]:block tw:[&_.relic-menu_.relic-list_li>span]:text-[11px] tw:[&_.relic-menu_.relic-list_li>span]:[line-height:1.65] tw:[&_.relic-menu_.relic-list_li>span]:text-[#647365]',
    'tw:[&_.relic-menu_.relic-list_li>small]:[grid-column:2] tw:[&_.relic-menu_.relic-list_li>small]:block',
    'tw:[&_.variant-toolbar>.text-button]:text-[12px] tw:[&_.variant-toolbar>.text-button]:[margin:8px_0]',
    'tw:[&_.tactical-panel]:flex tw:[&_.tactical-panel]:flex-col tw:[&_.tactical-panel]:gap-2.5 tw:[&_.tactical-panel]:p-4 tw:[&_.tactical-panel]:[margin:0_0_12px]',
    'tw:[&_.tactical-heading]:gap-2.5',
    'tw:[&_.tactical-heading>img]:w-13 tw:[&_.tactical-heading>img]:h-13',
    'tw:[&_.tactical-heading_h3]:[margin:0_0_4px] tw:[&_.tactical-heading_h3]:text-[15px]',
    'tw:[&_.tactical-heading_strong]:[margin:0_0_4px] tw:[&_.tactical-heading_strong]:text-[15px]',
    'tw:[&_.tactical-heading_p]:text-[11px] tw:[&_.tactical-heading_p]:m-0',
    'tw:[&_.tactical-counters]:justify-between tw:[&_.tactical-counters]:gap-2',
    'tw:[&_.tactical-counters_span]:text-[11px]',
    'tw:[&_.tactical-counters_strong]:text-[18px]',
    'tw:[&_.combat-stats]:gap-2 tw:[&_.combat-stats]:text-[11px] tw:[&_.combat-stats]:flex-wrap',
    'tw:[&_.combat-stats_strong]:text-[15px]',
    'tw:[&_.combat-sources]:text-[11px]',
    'tw:[&_.tactical-event]:m-0 tw:[&_.tactical-event]:text-[11px] tw:[&_.tactical-event]:[line-height:1.65]',
    'tw:[&_.tactical-plan]:m-0 tw:[&_.tactical-plan]:text-[11px] tw:[&_.tactical-plan]:[line-height:1.65]',
    'tw:[&_.tactical-panel>.text-button]:text-left tw:[&_.tactical-panel>.text-button]:m-0 tw:[&_.tactical-panel>.text-button]:[padding:5px_0] tw:[&_.tactical-panel>.text-button]:text-[11px] tw:[&_.tactical-panel>.text-button]:min-h-7.5',
    'tw:[&_.retreat-button]:[display:inline-flex] tw:[&_.retreat-button]:items-center tw:[&_.retreat-button]:[justify-content:center] tw:[&_.retreat-button]:gap-2.5 tw:[&_.retreat-button]:min-h-11 tw:[&_.retreat-button]:[padding:11px_18px] tw:[&_.retreat-button]:border tw:[&_.retreat-button]:border-solid tw:[&_.retreat-button]:border-[#c8cebf] tw:[&_.retreat-button]:[border-radius:11px] tw:[&_.retreat-button]:bg-[#f9faf3] tw:[&_.retreat-button]:text-[#586449] tw:[&_.retreat-button]:text-[12px] tw:[&_.retreat-button]:cursor-pointer tw:[&_.retreat-button]:w-full tw:[&_.retreat-button]:[margin:12px_0]',
    'tw:[&_.battle-reference-actions_.text-button]:flex tw:[&_.battle-reference-actions_.text-button]:items-center tw:[&_.battle-reference-actions_.text-button]:[justify-content:center] tw:[&_.battle-reference-actions_.text-button]:min-h-10 tw:[&_.battle-reference-actions_.text-button]:m-0 tw:[&_.battle-reference-actions_.text-button]:[padding:8px_6px] tw:[&_.battle-reference-actions_.text-button]:bg-[#edf2e7] tw:[&_.battle-reference-actions_.text-button]:border tw:[&_.battle-reference-actions_.text-button]:border-solid tw:[&_.battle-reference-actions_.text-button]:border-[#d2ddc9] tw:[&_.battle-reference-actions_.text-button]:[border-radius:9px] tw:[&_.battle-reference-actions_.text-button]:text-[#3a593f] tw:[&_.battle-reference-actions_.text-button]:text-[11px] tw:[&_.battle-reference-actions_.text-button]:text-center',
    'tw:[&_.battle-reference-actions_.text-button:hover]:bg-[#dfe9d6] tw:[&_.battle-reference-actions_.text-button:hover]:border-[#9eb48e]',
    'tw:[&_.battle-reference-actions_.text-button:focus-visible]:[outline:2px_solid_#557a48] tw:[&_.battle-reference-actions_.text-button:focus-visible]:[outline-offset:2px]',
    'tw:[@media(max-width:_900px)]:[&_.battle-reference-actions_.text-button]:min-h-11',
    'tw:[&_.mirror-heading]:min-w-0',
    'tw:[&_.mirror-heading>h3]:[margin:0_0_10px] tw:[&_.mirror-heading>h3]:text-[15px]',
    'tw:[&_.mirror-enemies]:[grid-template-columns:minmax(0,_1fr)] tw:[&_.mirror-enemies]:gap-2',
    'tw:[&_.mirror-enemy]:min-w-0 tw:[&_.mirror-enemy]:gap-2.5 tw:[&_.mirror-enemy]:p-2.5',
    'tw:[&_.mirror-enemy>img]:w-11 tw:[&_.mirror-enemy>img]:h-12 tw:[&_.mirror-enemy>img]:[flex:0_0_44px] tw:[&_.mirror-enemy>img]:object-contain',
    'tw:[&_.mirror-enemy>div]:grid tw:[&_.mirror-enemy>div]:[grid-template-columns:minmax(0,_1fr)_auto] tw:[&_.mirror-enemy>div]:[gap:4px_8px] tw:[&_.mirror-enemy>div]:min-w-0 tw:[&_.mirror-enemy>div]:[flex:1]',
    'tw:[&_.mirror-enemy-name]:text-[13px] tw:[&_.mirror-enemy-name]:[overflow-wrap:anywhere]',
    'tw:[&_.mirror-enemy-health]:text-[12px] tw:[&_.mirror-enemy-health]:whitespace-nowrap tw:[&_.mirror-enemy-health]:[font-variant-numeric:tabular-nums]',
    'tw:[&_.mirror-enemy_p]:[grid-column:1_/_-1] tw:[&_.mirror-enemy_p]:min-w-0 tw:[&_.mirror-enemy_p]:text-[11px] tw:[&_.mirror-enemy_p]:[line-height:1.6] tw:[&_.mirror-enemy_p]:[overflow-wrap:anywhere] tw:[&_.mirror-enemy_p]:m-0',
    'tw:[&_.mirror-beat]:text-[11px] tw:[&_.mirror-beat]:[line-height:1.6] tw:[&_.mirror-beat]:[margin:10px_0_0]',
  ].join(' '),
  'tactical-panel': [
    'tw:border tw:border-solid tw:border-[#d9dfd9] tw:rounded-2xl tw:p-4.5 tw:[margin:18px_0] tw:bg-[#fbfcf8] tw:grid tw:[grid-template-columns:minmax(0,_1fr)_minmax(0,_1fr)] tw:[gap:12px_24px] tw:[box-shadow:0_6px_22px_#26382d05]',
    'tw:[@media(max-width:_650px)]:[grid-template-columns:minmax(0,_1fr)] tw:[@media(max-width:_650px)]:p-3.5',
  ].join(' '),
  'tactical-heading': [
    'tw:flex tw:items-center tw:gap-3.5',
    'tw:[&>img]:w-19 tw:[&>img]:h-19 tw:[&>img]:object-contain',
    'tw:[&_h3]:[margin:4px_0]',
    'tw:[&_p]:[margin:4px_0] tw:[&_p]:text-[13px] tw:[&_p]:[line-height:1.6]',
  ].join(' '),
  'tactical-event': ['tw:text-[13px] tw:[line-height:1.6] tw:m-0'].join(' '),
  'tactical-plan': [
    'tw:text-[13px] tw:[line-height:1.6] tw:m-0 tw:[grid-column:1_/_-1] tw:text-muted',
  ].join(' '),
  'tactical-counters': [
    'tw:flex tw:gap-6 tw:items-center tw:[justify-content:flex-end] tw:flex-wrap',
    'tw:[&_span]:flex tw:[&_span]:flex-col tw:[&_span]:gap-1.5 tw:[&_span]:text-[12px]',
    'tw:[&_strong]:text-[22px]',
    'tw:[@media(max-width:_650px)]:justify-start',
  ].join(' '),
  'tactical-controls': [
    'tw:flex tw:gap-2 tw:flex-wrap',
    'tw:[&_button]:flex tw:[&_button]:items-center tw:[&_button]:gap-1.5 tw:[&_button]:[padding:10px_12px] tw:[&_button]:border tw:[&_button]:border-solid tw:[&_button]:border-line tw:[&_button]:[border-radius:10px] tw:[&_button]:text-[12px]',
    'tw:[&_img]:w-7.5 tw:[&_img]:h-7.5 tw:[&_img]:object-contain',
    'tw:[@media(max-width:_650px)]:[&_button]:[flex:1_1_auto] tw:[@media(max-width:_650px)]:[&_button]:[justify-content:center]',
  ].join(' '),
  'tactical-victory': ['tw:p-3.5 tw:bg-[#eaf4ef] tw:[border-radius:10px]'].join(' '),
  'combat-stats': [
    'tw:grid tw:[grid-template-columns:repeat(3,_minmax(0,_1fr))] tw:gap-2 tw:[padding:12px_0]',
    'tw:[&_span]:grid tw:[&_span]:gap-1 tw:[&_span]:text-[0.85em]',
    'tw:[&_strong]:text-[1.4em]',
  ].join(' '),
  'combat-sources': [
    'tw:mb-3 tw:text-[0.85em]',
    'tw:[&_summary]:cursor-pointer',
    'tw:[&_ul]:[padding-inline-start:18px]',
    'tw:[&_li]:[margin-block:8px]',
  ].join(' '),
  'action-dock': [
    'tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])_.skill-bubble]:left-auto tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])_.skill-bubble]:right-0 tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])_.skill-bubble]:[transform:none]',
    'tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])>[data-tool]]:[flex-basis:calc((100%_-_24px)/5)] tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])>[data-tool]]:[width:calc((100%_-_24px)/5)] tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])>.dock-skill]:[flex-basis:calc((100%_-_24px)/5)] tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])>.dock-skill]:[width:calc((100%_-_24px)/5)] tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])>.mode-cycle]:[flex-basis:calc((100%_-_24px)/5)] tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])>.mode-cycle]:[width:calc((100%_-_24px)/5)] tw:[@media(max-width:_389px)]:[&:has(>[data-tool=sonar])>.dock-skill>button]:w-full',
    'tw:[position:fixed] tw:bottom-0 tw:left-0 tw:right-0 tw:[z-index:30] tw:[min-height:var(--dock-space)] tw:[padding:9px_16px_calc(9px_+_env(safe-area-inset-bottom,_0px))] tw:flex tw:items-center tw:[justify-content:center] tw:gap-2.5 tw:bg-[#eef1edfa] tw:[border-top:1px_solid_#cbd5ca] tw:[box-shadow:0_-8px_28px_#23382a0b] tw:[backdrop-filter:blur(16px)]',
    'tw:[&_.dock-slot]:relative tw:[&_.dock-slot]:[flex:0_1_104px] tw:[&_.dock-slot]:w-26 tw:[&_.dock-slot]:h-19 tw:[&_.dock-slot]:min-h-11 tw:[&_.dock-slot]:flex tw:[&_.dock-slot]:flex-col tw:[&_.dock-slot]:items-center tw:[&_.dock-slot]:[justify-content:center] tw:[&_.dock-slot]:gap-0.5 tw:[&_.dock-slot]:[padding:5px_8px] tw:[&_.dock-slot]:border tw:[&_.dock-slot]:border-solid tw:[&_.dock-slot]:border-[#d2dbcf] tw:[&_.dock-slot]:[border-radius:13px] tw:[&_.dock-slot]:bg-[#fffefb] tw:[&_.dock-slot]:text-[#284535] tw:[&_.dock-slot]:cursor-pointer tw:[&_.dock-slot]:text-[12px] tw:[&_.dock-slot]:[transition:background-color_0.15s_ease,_border-color_0.15s_ease,_box-shadow_0.15s_ease,_transform_0.15s_ease]',
    'tw:[&_.dock-slot>img]:w-8.5 tw:[&_.dock-slot>img]:h-8.5 tw:[&_.dock-slot>img]:object-contain',
    'tw:[&_.dock-slot>svg]:w-8.5 tw:[&_.dock-slot>svg]:h-8.5 tw:[&_.dock-slot>svg]:object-contain',
    'tw:[&_.dock-slot>strong]:text-[12px] tw:[&_.dock-slot>strong]:font-semibold tw:[&_.dock-slot>strong]:[line-height:1.2] tw:[&_.dock-slot>strong]:max-w-full tw:[&_.dock-slot>strong]:overflow-hidden tw:[&_.dock-slot>strong]:whitespace-nowrap tw:[&_.dock-slot>strong]:[text-overflow:ellipsis]',
    'tw:[&_.tool-label]:text-[12px] tw:[&_.tool-label]:font-semibold tw:[&_.tool-label]:[line-height:1.2] tw:[&_.tool-label]:max-w-full tw:[&_.tool-label]:overflow-hidden tw:[&_.tool-label]:whitespace-nowrap tw:[&_.tool-label]:[text-overflow:ellipsis]',
    'tw:[&_.dock-slot_small]:text-[9px] tw:[&_.dock-slot_small]:[line-height:1.1] tw:[&_.dock-slot_small]:text-[#647466] tw:[&_.dock-slot_small]:max-w-22.5 tw:[&_.dock-slot_small]:overflow-hidden tw:[&_.dock-slot_small]:[text-overflow:ellipsis] tw:[&_.dock-slot_small]:whitespace-nowrap',
    'tw:[&_.mode-cycle]:bg-[#284e3b] tw:[&_.mode-cycle]:border-[#284e3b] tw:[&_.mode-cycle]:text-[white]',
    'tw:[&_.mode-cycle_small]:text-[#d0dfc6]',
    'tw:[&_.mode-cycle_svg]:[width:23px] tw:[&_.mode-cycle_svg]:[height:23px]',
    'tw:[&_[data-mode=flag]]:bg-[#875232] tw:[&_[data-mode=flag]]:border-[#875232]',
    'tw:[&_[data-mode=mark-safe]]:bg-[#366570] tw:[&_[data-mode=mark-safe]]:border-[#366570]',
    'tw:[&_[data-mode=chord]]:bg-[#655386] tw:[&_[data-mode=chord]]:border-[#655386]',
    'tw:[&_.tool-count]:absolute tw:[&_.tool-count]:[top:5px] tw:[&_.tool-count]:right-2 tw:[&_.tool-count]:[min-width:17px] tw:[&_.tool-count]:[border-radius:5px] tw:[&_.tool-count]:[padding:1px_3px] tw:[&_.tool-count]:bg-[#edf3e8] tw:[&_.tool-count]:text-[#355336] tw:[&_.tool-count]:text-[11px]',
    'tw:[&_.dock-slot[aria-pressed=true]]:[outline:3px_solid_#7da884] tw:[&_.dock-slot[aria-pressed=true]]:[outline-offset:1px]',
    'tw:[&_.dock-slot:disabled]:[opacity:0.45] tw:[&_.dock-slot:disabled]:[cursor:default] tw:[&_.dock-slot:disabled]:[transform:none] tw:[&_.dock-slot:disabled]:[box-shadow:none]',
    'tw:[&:has([data-tool][aria-pressed=true])_.dock-target-hint]:block',
    'tw:[@media(max-width:_650px)]:gap-1.5 tw:[@media(max-width:_650px)]:px-2.5',
    'tw:[@media(max-width:_650px)]:[&_.dock-slot]:w-17 tw:[@media(max-width:_650px)]:[&_.dock-slot]:[flex-basis:68px] tw:[@media(max-width:_650px)]:[&_.dock-slot]:[padding-inline:3px]',
    'tw:[@media(max-width:_650px)]:[&_.dock-slot>strong]:text-[10px]',
    'tw:[@media(max-width:_650px)]:[&_.tool-label]:text-[10px]',
    'tw:[&_.tactical-controls]:flex tw:[&_.tactical-controls]:gap-2 tw:[&_.tactical-controls]:m-0 tw:[&_.tactical-controls]:[padding:0_12px_0_0] tw:[&_.tactical-controls]:[border-right:1px_solid_#cbd5ca] tw:[&_.tactical-controls]:[flex:0_0_auto]',
    'tw:[&_.tactical-controls_.dock-slot]:w-25 tw:[&_.tactical-controls_.dock-slot]:[flex-basis:100px] tw:[&_.tactical-controls_.dock-slot]:text-[11px] tw:[&_.tactical-controls_.dock-slot]:whitespace-nowrap',
    'tw:[&_.tactical-controls_[data-control=end-turn]]:bg-[#345a40] tw:[&_.tactical-controls_[data-control=end-turn]]:border-[#345a40] tw:[&_.tactical-controls_[data-control=end-turn]]:text-[#fffef5]',
    'tw:[&_.tactical-controls_[data-control=end-turn]_small]:text-[#d3e3cc]',
    'tw:[@media(max-width:_900px)]:[&:has(.tactical-controls)]:flex-wrap tw:[@media(max-width:_900px)]:[&:has(.tactical-controls)]:[align-content:center] tw:[@media(max-width:_900px)]:[&:has(.tactical-controls)]:[row-gap:6px]',
    'tw:[@media(max-width:_900px)]:[&_.tactical-controls]:w-full tw:[@media(max-width:_900px)]:[&_.tactical-controls]:[justify-content:center] tw:[@media(max-width:_900px)]:[&_.tactical-controls]:[border:0] tw:[@media(max-width:_900px)]:[&_.tactical-controls]:p-0 tw:[@media(max-width:_900px)]:[&_.tactical-controls]:gap-1.5',
    'tw:[@media(max-width:_900px)]:[&_.tactical-controls_.dock-slot]:h-14.5 tw:[@media(min-width:_390px)_and_(max-width:_900px)]:[&_.tactical-controls_.dock-slot]:w-22 tw:[@media(min-width:_390px)_and_(max-width:_900px)]:[&_.tactical-controls_.dock-slot]:[flex-basis:88px] tw:[@media(min-width:_390px)_and_(max-width:_900px)]:[&_.tactical-controls_.dock-slot]:text-[10px]',
    'tw:[@media(max-width:_900px)]:[&_.tactical-controls_.dock-slot>img]:w-6 tw:[@media(max-width:_900px)]:[&_.tactical-controls_.dock-slot>img]:h-6',
    'tw:[@media(max-width:_900px)]:[&_.tactical-controls_.dock-slot[data-control=end-turn]]:[gap:1px]',
    'tw:[@media(max-width:_900px)]:[&_.tactical-controls_.dock-slot[data-control=end-turn]>img]:hidden',
    'tw:[@media(max-width:_900px)]:[&_.tactical-controls_.dock-slot[data-control=end-turn]_strong]:text-[11px]',
    'tw:[@media(max-width:_389px)]:[&_.tactical-controls_.dock-slot]:w-17 tw:[@media(max-width:_389px)]:[&_.tactical-controls_.dock-slot]:[flex-basis:68px] tw:[@media(max-width:_389px)]:[&_.tactical-controls_.dock-slot]:text-[9px]',
    'tw:[&_.dock-skill>.dock-slot[aria-disabled=true]]:[opacity:0.45] tw:[&_.dock-skill>.dock-slot[aria-disabled=true]]:[filter:grayscale(1)] tw:[&_.dock-skill>.dock-slot[aria-disabled=true]]:[cursor:help]',
    'tw:[@media(hover:_hover)]:[&_.dock-slot:not(:disabled):not([aria-disabled=true]):hover]:bg-[#e5eddf] tw:[@media(hover:_hover)]:[&_.dock-slot:not(:disabled):not([aria-disabled=true]):hover]:border-[#91a886] tw:[@media(hover:_hover)]:[&_.dock-slot:not(:disabled):not([aria-disabled=true]):hover]:[box-shadow:0_3px_10px_#344c3020] tw:[@media(hover:_hover)]:[&_.dock-slot:not(:disabled):not([aria-disabled=true]):hover]:[transform:translateY(-2px)]',
    'tw:[@media(hover:_hover)]:[&_.mode-cycle:not(:disabled):hover]:bg-[#416b4c] tw:[@media(hover:_hover)]:[&_.mode-cycle:not(:disabled):hover]:border-[#6f926e] tw:[@media(hover:_hover)]:[&_.mode-cycle:not(:disabled):hover]:text-[#fffef5]',
    'tw:[@media(hover:_hover)]:[&_.tactical-controls_[data-control=end-turn]:not(:disabled):hover]:bg-[#416b4c] tw:[@media(hover:_hover)]:[&_.tactical-controls_[data-control=end-turn]:not(:disabled):hover]:border-[#6f926e] tw:[@media(hover:_hover)]:[&_.tactical-controls_[data-control=end-turn]:not(:disabled):hover]:text-[#fffef5]',
    'tw:[&_.dock-slot:not(:disabled):not([aria-disabled=true]):active]:[transform:translateY(1px)] tw:[&_.dock-slot:not(:disabled):not([aria-disabled=true]):active]:[box-shadow:inset_0_1px_4px_#29412b24]',
    'tw:[&_.dock-slot:focus-visible]:[outline:2px_solid_#648253] tw:[&_.dock-slot:focus-visible]:[outline-offset:3px]',
    'tw:[&_.dock-slot[aria-disabled=true]]:[transform:none] tw:[&_.dock-slot[aria-disabled=true]]:[box-shadow:none]',
    'tw:[@media(prefers-reduced-motion:_reduce)]:[&_.dock-slot]:[transition:none]',
  ].join(' '),
  'dock-skill': [
    'tw:[flex:0_1_104px] tw:relative',
    'tw:[&>summary]:list-none',
    'tw:[&>summary::-webkit-details-marker]:hidden',
    'tw:[@media(max-width:_650px)]:[flex-basis:68px]',
    'tw:[&[data-skill-tip]_.skill-bubble]:block',
    'tw:[&>button:focus-visible_+_.skill-bubble]:block',
    'tw:[@media(hover:_hover)]:[&:hover_.skill-bubble]:block',
    'tw:[&:has(.dock-skill-panel:not([hidden]))_.skill-bubble]:hidden',
  ].join(' '),
  'dock-skill-panel': [
    'tw:absolute tw:[bottom:calc(100%_+_16px)] tw:[left:50%] tw:[transform:translateX(-50%)] tw:[width:min(300px,_85vw)] tw:p-4 tw:bg-[#fffffb] tw:border tw:border-solid tw:border-[#cbd8c6] tw:rounded-[18px] tw:[box-shadow:0_8px_36px_#23382a26] tw:[max-height:min(440px,_60dvh)] tw:[overflow:auto]',
    'tw:[&_.profession-skill]:m-0 tw:[&_.profession-skill]:p-0 tw:[&_.profession-skill]:[border:0] tw:[&_.profession-skill]:bg-transparent',
    'tw:[@media(max-width:_650px)]:left-auto tw:[@media(max-width:_650px)]:[right:-70px] tw:[@media(max-width:_650px)]:[transform:none] tw:[@media(max-width:_650px)]:[width:min(280px,_90vw)]',
    'tw:[&[hidden]]:hidden',
    'tw:[&_#skill-status]:[margin:10px_0_0] tw:[&_#skill-status]:p-2.5 tw:[&_#skill-status]:rounded-lg tw:[&_#skill-status]:bg-[#edf2e7] tw:[&_#skill-status]:text-[12px] tw:[&_#skill-status]:[line-height:1.65] tw:[&_#skill-status]:text-[#38533a] tw:[&_#skill-status]:[white-space:normal]',
  ].join(' '),
  'dock-target-hint': [
    'tw:hidden tw:absolute tw:[bottom:calc(100%_+_8px)] tw:[left:50%] tw:[transform:translateX(-50%)] tw:[max-width:min(580px,_90vw)] tw:[width:max-content] tw:border tw:border-solid tw:border-[#cbd8c6] tw:[padding:10px_16px] tw:rounded-xl tw:bg-[#fffefb] tw:[box-shadow:0_6px_20px_#23382a13] tw:text-[12px] tw:text-[#35523f]',
  ].join(' '),
  'compact-dock': [
    'tw:[&_.mode-cycle]:[flex-basis:200px] tw:[&_.mode-cycle]:w-50 tw:[&_.mode-cycle]:h-17',
    'tw:[@media(max-width:_650px)]:[&_.mode-cycle]:w-44 tw:[@media(max-width:_650px)]:[&_.mode-cycle]:[flex-basis:176px]',
  ].join(' '),
  'relic-menu': [
    'tw:[&>summary_img]:w-7 tw:[&>summary_img]:h-7 tw:[&>summary_img]:object-contain',
  ].join(' '),
  'retreat-button': [
    'tw:[display:inline-flex] tw:items-center tw:[justify-content:center] tw:gap-2.5 tw:min-h-11 tw:[padding:11px_18px] tw:border tw:border-solid tw:border-[#c8cebf] tw:[border-radius:11px] tw:bg-[#f9faf3] tw:text-[#586449] tw:text-[12px] tw:cursor-pointer',
    'tw:[&:hover]:bg-[#e8eddf] tw:[&:hover]:border-[#99ac89]',
    'tw:[&>span]:text-[20px]',
  ].join(' '),
  'run-overview': [
    'tw:p-4 tw:border tw:border-solid tw:border-[#d7dfd2] tw:rounded-2xl tw:bg-[#fffef9] tw:mb-3',
    'tw:[&_.variant-heading]:[margin:0_0_12px] tw:[&_.variant-heading]:gap-2',
    'tw:[&_.variant-heading_h2]:text-[20px] tw:[&_.variant-heading_h2]:m-0',
    'tw:[&_.variant-note]:text-[11px] tw:[&_.variant-note]:[margin:4px_0]',
    'tw:[&_.variant-metrics]:grid tw:[&_.variant-metrics]:[grid-template-columns:minmax(0,_1fr)] tw:[&_.variant-metrics]:gap-0 tw:[&_.variant-metrics]:[margin:10px_0] tw:[&_.variant-metrics]:[padding:4px_0]',
    'tw:[&_.variant-metric]:[flex-direction:row] tw:[&_.variant-metric]:items-center tw:[&_.variant-metric]:justify-between tw:[&_.variant-metric]:gap-3 tw:[&_.variant-metric]:[padding:8px_0]',
    'tw:[&_.variant-metric_+_.variant-metric]:[border-top:1px_solid_#e7e9e0]',
    'tw:[&_.variant-metrics_strong]:[flex:0_0_auto] tw:[&_.variant-metrics_strong]:text-[18px] tw:[&_.variant-metrics_strong]:[line-height:1.3] tw:[&_.variant-metrics_strong]:[font-variant-numeric:tabular-nums] tw:[&_.variant-metrics_strong]:whitespace-nowrap',
    'tw:[&_.variant-metrics_span]:text-[12px]',
  ].join(' '),
  'battle-reference-actions': ['tw:grid tw:[grid-template-columns:1fr_1fr] tw:gap-2'].join(' '),
  'skill-bubble': [
    'tw:hidden tw:absolute tw:[bottom:calc(100%_+_12px)] tw:[left:50%] tw:[transform:translateX(-50%)] tw:[width:max-content] tw:[max-width:min(260px,_calc(100vw_-_32px))] tw:[padding:11px_14px] tw:border tw:border-solid tw:border-[#ccd7c4] tw:[border-radius:11px] tw:bg-[#fffef8] tw:text-[#354735] tw:[box-shadow:0_5px_20px_#142e2828] tw:text-[12px] tw:[line-height:1.7] tw:[white-space:normal] tw:[z-index:5] tw:[pointer-events:none]',
    'tw:[@media(max-width:_650px)]:[max-width:min(240px,_calc(100vw_-_100px))]',
  ].join(' '),
  'sonar-dock': [
    'tw:[&_.sonar-mode]:[display:contents]',
    'tw:[&_.sonar-scan]:text-[#237a77]',
    'tw:[&_.sonar-scan[aria-pressed=true]]:border-[#237a77] tw:[&_.sonar-scan[aria-pressed=true]]:bg-[#dfeee5] tw:[&_.sonar-scan[aria-pressed=true]]:[box-shadow:0_0_0_2px_#237a7725]',
    'tw:[&_[data-control=scan]]:[touch-action:none] tw:[&_[data-control=scan]]:[user-select:none]',
  ].join(' '),
  'sonar-target-hint': [
    'tw:max-w-95 tw:text-[12px] tw:[line-height:1.6] tw:text-muted tw:[margin:0_0_0_16px]',
    'tw:[@media(max-width:_800px)]:max-w-37.5 tw:[@media(max-width:_800px)]:text-[10px] tw:[@media(max-width:_800px)]:ml-1',
  ].join(' '),
}
