/** Guidance and Sonar presentation utility groups; keep complete classes visible to the Tailwind scanner. */
export const guidanceStyles = {
  'guidance-dialog': [
    'tw:[&.sonar-dialog]:[width:min(650px,_calc(100vw_-_28px))]',
    'tw:[width:min(980px,_calc(100vw_-_32px))] tw:max-w-none tw:[max-height:calc(100dvh_-_32px)] tw:p-0 tw:border tw:border-solid tw:border-[#d9dfd1] tw:[border-radius:24px] tw:bg-[var(--dialog-surface)] tw:text-[#253c2e] tw:[box-shadow:0_28px_100px_#11271e66] tw:[overflow:auto]',
    'tw:[&::backdrop]:bg-[#12251ee0] tw:[&::backdrop]:[backdrop-filter:blur(7px)]',
    'tw:[@media(max-width:_650px)]:[width:calc(100vw_-_16px)] tw:[@media(max-width:_650px)]:[max-height:calc(100dvh_-_16px)] tw:[@media(max-width:_650px)]:rounded-[18px]',
  ].join(' '),
  'prologue-dialog': [
    'tw:[width:min(980px,_calc(100vw_-_32px))] tw:max-w-none tw:[max-height:calc(100dvh_-_32px)] tw:p-0 tw:border tw:border-solid tw:border-[#4a4940] tw:[border-radius:24px] tw:bg-[var(--prologue-surface)] tw:text-[#f3ead6] tw:[box-shadow:0_28px_100px_#11271e66] tw:[overflow:auto]',
    'tw:[&::backdrop]:bg-[#12251ee0] tw:[&::backdrop]:[backdrop-filter:blur(7px)]',
    'tw:[&[data-focus=objective]_.scene-objective]:[outline:1px_solid_#d2bb73] tw:[&[data-focus=objective]_.scene-objective]:[box-shadow:0_0_18px_#e2c7798a] tw:[&[data-focus=objective]_.scene-objective]:[animation:practice-pulse_2s_ease-in-out_infinite]',
    'tw:[&[data-focus=player]_.scene-hero_img]:[transform:scale(1.12)] tw:[&[data-focus=player]_.scene-hero_img]:[filter:drop-shadow(0_0_24px_#c5d8a647)]',
    'tw:[&[data-focus=boss]_.scene-enemy_img]:[transform:scale(1.12)] tw:[&[data-focus=boss]_.scene-enemy_img]:[filter:drop-shadow(0_0_24px_#c5d8a647)]',
    'tw:[&[data-focus=field]_.scene-map]:[transform:perspective(700px)_rotateX(0)_scale(1.05)]',
    'tw:[@media(max-width:_650px)]:[width:calc(100vw_-_16px)] tw:[@media(max-width:_650px)]:[max-height:calc(100dvh_-_16px)] tw:[@media(max-width:_650px)]:rounded-[18px]',
    'tw:[@media(prefers-reduced-motion:_reduce)]:[&[data-focus=objective]_.scene-objective]:[animation:none]',
  ].join(' '),
  'guidance-header': [
    'tw:flex tw:items-start tw:justify-between tw:gap-5 tw:[padding:28px_32px_20px]',
    'tw:[&_h2]:[margin:8px_0_0] tw:[&_h2]:text-[27px] tw:[&_h2]:font-semibold tw:[&_h2]:[letter-spacing:-0.03em]',
    'tw:[@media(max-width:_650px)]:[padding:18px_18px_14px] tw:[@media(max-width:_650px)]:gap-2.5',
    'tw:[@media(max-width:_650px)]:[&_h2]:text-[21px]',
  ].join(' '),
  'prologue-header': [
    'tw:flex tw:items-start tw:justify-between tw:gap-5 tw:[padding:28px_32px_20px]',
    'tw:[&_h2]:[margin:8px_0_0] tw:[&_h2]:text-[27px] tw:[&_h2]:font-semibold tw:[&_h2]:[letter-spacing:-0.03em]',
    'tw:[&_p]:text-[#a6ab9f] tw:[&_p]:text-[12px] tw:[&_p]:[margin:9px_0_0] tw:[&_p]:[letter-spacing:0.13em]',
    'tw:[&_.text-button]:text-[#b7c1b3] tw:[&_.text-button]:min-h-11',
    'tw:[@media(max-width:_650px)]:[padding:18px_18px_14px] tw:[@media(max-width:_650px)]:gap-2.5',
    'tw:[@media(max-width:_650px)]:[&_h2]:text-[21px]',
    'tw:[@media(max-width:_650px)]:[&>button]:text-[10px] tw:[@media(max-width:_650px)]:[&>button]:shrink-0 tw:[@media(max-width:_650px)]:[&>button]:p-0',
  ].join(' '),
  'guidance-eyebrow': [
    'tw:text-[#829077] tw:text-[10px] tw:[letter-spacing:0.14em] tw:font-semibold',
  ].join(' '),
  'guidance-close': [
    'tw:border tw:border-solid tw:border-[#d9dfd1] tw:[border-radius:50%] tw:w-11 tw:h-11 tw:shrink-0 tw:text-[24px] tw:bg-[#fff] tw:text-[#526851] tw:cursor-pointer',
  ].join(' '),
  'lesson-progress': [
    'tw:flex tw:[gap:5px] tw:[padding:0_32px]',
    'tw:[&_span]:[height:3px] tw:[&_span]:[flex:1] tw:[&_span]:[border-radius:2px] tw:[&_span]:bg-[#e0e5da]',
    'tw:[&_.done]:bg-[#8da889]',
    'tw:[&_.current]:bg-[#b68b48]',
    'tw:[@media(max-width:_650px)]:px-4.5',
  ].join(' '),
  'guidance-layout': [
    'tw:grid tw:[grid-template-columns:0.85fr_1.15fr] tw:gap-8 tw:[padding:28px_32px]',
    'tw:[@media(max-width:_650px)]:[grid-template-columns:1fr] tw:[@media(max-width:_650px)]:gap-4 tw:[@media(max-width:_650px)]:[padding:16px_18px]',
  ].join(' '),
  'lesson-number': [
    'tw:text-[46px] tw:text-[#a6b49b] tw:[font-family:Georgia,_serif] tw:[font-style:italic] tw:[line-height:1]',
    'tw:[@media(max-width:_650px)]:text-[25px] tw:[@media(max-width:_650px)]:[float:left] tw:[@media(max-width:_650px)]:mr-2.5',
  ].join(' '),
  'lesson-note': [
    'tw:[&_h3]:text-[21px] tw:[&_h3]:[margin:16px_0]',
    'tw:[&_p]:text-[14px] tw:[&_p]:[line-height:1.95]',
    'tw:[&>small]:text-[10px] tw:[&>small]:text-[#829077]',
    'tw:[@media(max-width:_650px)]:[&_h3]:text-[17px] tw:[@media(max-width:_650px)]:[&_h3]:[margin:0_0_10px]',
    'tw:[@media(max-width:_650px)]:[&_p]:text-[12px] tw:[@media(max-width:_650px)]:[&_p]:[line-height:1.8] tw:[@media(max-width:_650px)]:[&_p]:[margin:10px_0]',
    'tw:[@media(max-width:_650px)]:[&_.lesson-feedback]:min-h-0',
    'tw:[@media(max-width:_650px)]:[&>small]:text-[9px]',
  ].join(' '),
  'lesson-feedback': ['tw:min-h-11.5 tw:text-[#678347] tw:font-medium'].join(' '),
  'practice-vitals': [
    'tw:[border-top:1px_solid_#dce4d4] tw:[border-bottom:1px_solid_#dce4d4] tw:[padding:12px_0] tw:[margin:16px_0] tw:[font-variant-numeric:tabular-nums]',
  ].join(' '),
  'lesson-workspace': ['tw:min-w-0 tw:[align-self:center]'].join(' '),
  'practice-dock': [
    'tw:flex tw:[justify-content:center] tw:gap-2 tw:mt-4.5',
    'tw:[&_button]:min-h-15 tw:[&_button]:border tw:[&_button]:border-solid tw:[&_button]:border-[#c9d6bf] tw:[&_button]:rounded-xl tw:[&_button]:[padding:7px_10px] tw:[&_button]:bg-[#fffef8] tw:[&_button]:text-[#39523b] tw:[&_button]:flex tw:[&_button]:flex-col tw:[&_button]:items-center tw:[&_button]:[justify-content:center] tw:[&_button]:cursor-pointer tw:[&_button]:[flex:1] tw:[&_button]:min-w-0',
    'tw:[&_.mode-cycle]:bg-[#365f43] tw:[&_.mode-cycle]:text-[#fff]',
    'tw:[&_img]:w-7.5 tw:[&_img]:h-7.5 tw:[&_img]:object-contain',
    'tw:[&_svg]:w-5.5 tw:[&_svg]:h-5.5',
    'tw:[&_small]:text-[9px]',
    'tw:[&_strong]:text-[11px] tw:[&_strong]:whitespace-nowrap',
    'tw:[&_span]:text-[11px] tw:[&_span]:whitespace-nowrap',
    'tw:[&_.selected]:[outline:2px_solid_#b68b48]',
    'tw:[@media(max-width:_650px)]:mt-2.5 tw:[@media(max-width:_650px)]:[gap:5px]',
  ].join(' '),
  'guidance-footer': [
    'tw:flex tw:items-center tw:justify-between tw:gap-4 tw:[border-top:1px_solid_#dce3d5] tw:[padding:18px_32px]',
    'tw:[&>span]:text-[10px] tw:[&>span]:text-[#84917a]',
    'tw:[&_.primary-button]:bg-[#345d41] tw:[&_.primary-button]:min-h-11 tw:[&_.primary-button]:[padding:12px_24px]',
    'tw:[@media(max-width:_650px)]:[padding:12px_18px] tw:[@media(max-width:_650px)]:gap-2 tw:[@media(max-width:_650px)]:sticky tw:[@media(max-width:_650px)]:bottom-0 tw:[@media(max-width:_650px)]:bg-[#f8f9f3]',
    'tw:[@media(max-width:_650px)]:[&>span]:hidden',
  ].join(' '),
  'prologue-footer': [
    'tw:flex tw:items-center tw:justify-between tw:gap-4 tw:[border-top:1px_solid_#dce3d5] tw:[padding:18px_32px] tw:border-[#b7b08b22]',
    'tw:[&_.primary-button]:bg-[#345d41] tw:[&_.primary-button]:min-h-11 tw:[&_.primary-button]:[padding:12px_24px]',
    'tw:[&_.text-button]:text-[#b7c1b3] tw:[&_.text-button]:min-h-11',
    'tw:[&>span]:text-[16px] tw:[&>span]:text-[#d0bc87] tw:[&>span]:[font-variant-numeric:tabular-nums]',
    'tw:[&_i]:[font-style:normal] tw:[&_i]:text-[#69796e]',
    'tw:[@media(max-width:_650px)]:[padding:12px_18px] tw:[@media(max-width:_650px)]:gap-2 tw:[@media(max-width:_650px)]:sticky tw:[@media(max-width:_650px)]:bottom-0 tw:[@media(max-width:_650px)]:bg-[#171f24]',
  ].join(' '),
  'prologue-stage': [
    'tw:relative tw:min-h-70 tw:[padding:24px_30px] tw:grid tw:[grid-template-columns:1fr_1.8fr_1fr] tw:items-center tw:gap-5 tw:overflow-hidden tw:bg-[radial-gradient(ellipse_at_50%_70%,_#4a554134,_transparent_65%)]',
    'tw:[@media(max-width:_650px)]:[min-height:175px] tw:[@media(max-width:_650px)]:[grid-template-columns:65px_1fr_90px] tw:[@media(max-width:_650px)]:gap-2 tw:[@media(max-width:_650px)]:[padding:12px_14px]',
  ].join(' '),
  'scene-portrait': [
    'tw:flex tw:flex-col tw:items-center tw:relative tw:[z-index:1]',
    'tw:[&_img]:w-full tw:[&_img]:max-w-47.5 tw:[&_img]:h-45 tw:[&_img]:object-contain tw:[&_img]:[filter:drop-shadow(0_14px_20px_#0006)] tw:[&_img]:[transition:transform_0.6s_ease,_filter_0.6s_ease]',
    'tw:[&_span]:text-[10px] tw:[&_span]:text-[#a2af9e] tw:[&_span]:mt-4 tw:[&_span]:[letter-spacing:0.08em]',
    'tw:[@media(max-width:_650px)]:[&_img]:h-25',
    'tw:[@media(max-width:_650px)]:[&_span]:hidden',
    'tw:[@media(prefers-reduced-motion:_reduce)]:[&_img]:[transition:none]',
  ].join(' '),
  'prologue-dialogue': [
    'tw:grid tw:[grid-template-columns:65px_1fr] tw:gap-5 tw:[align-items:start] tw:[padding:24px_32px] tw:[margin:0_24px_24px] tw:border tw:border-solid tw:border-[#b7b08b33] tw:bg-[#232f3090] tw:[border-radius:15px] tw:min-h-41',
    'tw:[&_strong]:text-[11px] tw:[&_strong]:text-[#cbb883] tw:[&_strong]:[letter-spacing:0.08em]',
    'tw:[&_p]:[margin:10px_0_0] tw:[&_p]:text-[16px] tw:[&_p]:[line-height:1.95] tw:[&_p]:[animation:dialogue-in_0.35s_ease_both]',
    'tw:[&[data-speaker=player]_p]:[font-style:italic] tw:[&[data-speaker=player]_p]:text-[#c7d8c9]',
    'tw:[@media(max-width:_650px)]:[grid-template-columns:36px_1fr] tw:[@media(max-width:_650px)]:gap-3 tw:[@media(max-width:_650px)]:[padding:17px_14px] tw:[@media(max-width:_650px)]:[margin:0_12px_16px] tw:[@media(max-width:_650px)]:[min-height:185px]',
    'tw:[@media(max-width:_650px)]:[&_p]:text-[14px] tw:[@media(max-width:_650px)]:[&_p]:[line-height:1.9]',
    'tw:[@media(prefers-reduced-motion:_reduce)]:[&_p]:[animation:none]',
  ].join(' '),
  'dialogue-portrait': [
    'tw:w-16 tw:h-16 tw:bg-[#d3dac412] tw:[border-radius:50%] tw:[padding:7px]',
    'tw:[&_img]:w-full tw:[&_img]:h-full tw:[&_img]:object-contain',
    'tw:[@media(max-width:_650px)]:w-9 tw:[@media(max-width:_650px)]:h-9 tw:[@media(max-width:_650px)]:[padding:3px]',
  ].join(' '),
  'battle-guide-hero': [
    'tw:flex tw:items-center tw:gap-6 tw:[padding:20px_28px] tw:bg-[#223b31] tw:rounded-2xl tw:text-[#f4f0db]',
    'tw:[&>img]:w-26 tw:[&>img]:h-29 tw:[&>img]:object-contain tw:[&>img]:[filter:drop-shadow(0_8px_12px_#0004)]',
    'tw:[&_span]:text-[10px] tw:[&_span]:[letter-spacing:0.15em] tw:[&_span]:text-[#b3c3a8]',
    'tw:[&_h3]:text-[28px] tw:[&_h3]:[margin:8px_0]',
    'tw:[&_p]:text-[#d6dfcf] tw:[&_p]:text-[12px] tw:[&_p]:m-0',
    'tw:[@media(max-width:_650px)]:p-4 tw:[@media(max-width:_650px)]:gap-3.5',
    'tw:[@media(max-width:_650px)]:[&>img]:w-19 tw:[@media(max-width:_650px)]:[&>img]:h-23',
    'tw:[@media(max-width:_650px)]:[&_h3]:text-[23px]',
  ].join(' '),
  'battle-guide-plan': [
    'tw:[padding:22px_0_8px]',
    'tw:[&_h3]:text-[16px] tw:[&_h3]:[margin:0_0_10px]',
    'tw:[&_p]:text-[13px] tw:[&_p]:[line-height:1.9] tw:[&_p]:text-[#536350] tw:[&_p]:m-0',
  ].join(' '),
  'battle-guide': ['tw:[&_h3]:[line-height:1.4]'].join(' '),
  'battle-guide-costs': [
    'tw:[&_h3]:text-[16px] tw:[&_h3]:[margin:0_0_10px]',
    'tw:[margin:22px_0_8px] tw:p-4.5 tw:bg-[#eaf0e3] tw:[border-radius:14px]',
    'tw:[&>div]:grid tw:[&>div]:[grid-template-columns:repeat(5,_1fr)] tw:[&>div]:gap-2',
    'tw:[&>div>span]:text-[11px] tw:[&>div>span]:flex tw:[&>div>span]:flex-col tw:[&>div>span]:gap-1.5',
    'tw:[&_strong]:text-[19px] tw:[&_strong]:text-[#34573d]',
    'tw:[&_p]:text-[11px] tw:[&_p]:[margin:16px_0_0]',
    'tw:[&_p_strong]:text-[12px]',
  ].join(' '),
  'battle-guide-cards': [
    'tw:[&_p]:text-[13px] tw:[&_p]:[line-height:1.9] tw:[&_p]:text-[#536350] tw:[&_p]:m-0',
    'tw:grid tw:[grid-template-columns:1fr_1fr] tw:gap-3',
    'tw:[&>section]:p-5 tw:[&>section]:border tw:[&>section]:border-solid tw:[&>section]:border-[#dae1d3] tw:[&>section]:[border-radius:14px] tw:[&>section]:bg-[#fffef9]',
    'tw:[&_h3]:text-[15px] tw:[&_h3]:[margin:8px_0_12px]',
    'tw:[@media(max-width:_650px)]:[grid-template-columns:1fr]',
    'tw:[@media(max-width:_650px)]:[&>section]:p-4',
  ].join(' '),
  'battle-guide-rules': [
    'tw:[&_p]:text-[13px] tw:[&_p]:[line-height:1.9] tw:[&_p]:text-[#536350] tw:[&_p]:m-0 tw:[&_p]:[padding:0_0_18px]',
    'tw:[border-bottom:1px_solid_#dce3d5]',
    'tw:[&_summary]:[padding:15px_0] tw:[&_summary]:text-[13px] tw:[&_summary]:cursor-pointer tw:[&_summary]:min-h-11',
  ].join(' '),
  'battle-guide-flow': [
    'tw:flex tw:list-none tw:gap-4 tw:[padding:14px_0_22px] tw:m-0',
    'tw:[&_li]:flex tw:[&_li]:gap-2 tw:[&_li]:items-center tw:[&_li]:[flex:1] tw:[&_li]:text-[12px] tw:[&_li]:text-[#38573e]',
    'tw:[&_li>span]:grid tw:[&_li>span]:[place-items:center] tw:[&_li>span]:w-6 tw:[&_li>span]:h-6 tw:[&_li>span]:shrink-0 tw:[&_li>span]:[border-radius:50%] tw:[&_li>span]:bg-[#dfe8d6] tw:[&_li>span]:[font-variant-numeric:tabular-nums]',
    'tw:[@media(max-width:_650px)]:gap-2',
    'tw:[@media(max-width:_650px)]:[&_li]:flex-col tw:[@media(max-width:_650px)]:[&_li]:items-start tw:[@media(max-width:_650px)]:[&_li]:text-[11px] tw:[@media(max-width:_650px)]:[&_li]:[line-height:1.6]',
  ].join(' '),
  'battle-guide-number': ['tw:text-[#a28c53] tw:text-[12px]'].join(' '),
  'boss-picture-steps': [
    'tw:grid tw:[grid-template-columns:repeat(3,_minmax(0,_1fr))] tw:gap-3.5 tw:list-none tw:m-0 tw:p-0',
    'tw:[&_li]:p-3.5 tw:[&_li]:bg-surface tw:[&_li]:border tw:[&_li]:border-solid tw:[&_li]:border-line tw:[&_li]:rounded-2xl',
    'tw:[&_p]:flex tw:[&_p]:[gap:9px] tw:[&_p]:[line-height:1.6] tw:[&_p]:[margin:14px_0_0]',
    'tw:[&_b]:text-[#47785a]',
    'tw:[@media(max-width:_620px)]:[grid-template-columns:1fr]',
    'tw:[@media(max-width:_620px)]:[&_li]:grid tw:[@media(max-width:_620px)]:[&_li]:[grid-template-columns:var(--picture-step-columns,_minmax(110px,_40%)_1fr)] tw:[@media(max-width:_620px)]:[&_li]:gap-3 tw:[@media(max-width:_620px)]:[&_li]:items-center',
    'tw:[@media(max-width:_620px)]:[&_p]:m-0',
  ].join(' '),
  'boss-mini-board': [
    'tw:grid tw:[grid-template-columns:repeat(5,_1fr)] tw:[gap:3px] tw:max-w-65 tw:m-auto',
    'tw:[&_span]:[aspect-ratio:1] tw:[&_span]:grid tw:[&_span]:[place-items:center] tw:[&_span]:bg-[#e9efe7] tw:[&_span]:[border-radius:5px] tw:[&_span]:min-w-0 tw:[&_span]:text-[#426d53] tw:[&_span]:text-[1.2rem]',
    'tw:[&_span.mini-danger]:bg-[#f1ddd4]',
    'tw:[&_img]:w-full tw:[&_img]:h-full tw:[&_img]:object-contain',
    'tw:[@media(max-width:_620px)]:w-full',
    'tw:[&_.mini-echo_img]:[opacity:0.45] tw:[&_.mini-echo_img]:[filter:sepia(1)_hue-rotate(180deg)]',
  ].join(' '),
  'boss-cost-line': ['tw:text-[0.8rem] tw:text-muted tw:[line-height:1.8] tw:[margin:18px_0]'].join(
    ' ',
  ),
  'sonar-main': [
    'tw:[--sonar-accent:#237a77] tw:[width:min(94%,_1760px)] tw:[margin:0_auto] tw:[padding:12px_0_36px]',
    'tw:[@media(max-width:_800px)]:[width:calc(100%_-_28px)]',
  ].join(' '),
  'sonar-heading': [
    'tw:flex tw:justify-between tw:gap-5 tw:items-center',
    'tw:[&_h1]:text-[clamp(30px,_2.2vw,_48px)] tw:[&_h1]:[margin:8px_0] tw:[&_h1]:[letter-spacing:-0.04em]',
    'tw:[&_p]:text-muted tw:[&_p]:[margin:6px_0_16px]',
    'tw:[&_.eyebrow]:text-[var(--sonar-accent)] tw:[&_.eyebrow]:[font:11px_var(--mono)] tw:[&_.eyebrow]:[letter-spacing:0.14em]',
    'tw:[@media(max-width:_800px)]:[&_.eyebrow]:hidden',
  ].join(' '),
  'sonar-difficulties': [
    'tw:flex tw:gap-1.5 tw:[margin:12px_0_20px] tw:flex-wrap',
    'tw:[&_button]:min-h-11 tw:[&_button]:[padding:10px_20px] tw:[&_button]:[border-radius:9px] tw:[&_button]:border tw:[&_button]:border-solid tw:[&_button]:border-transparent tw:[&_button]:bg-transparent',
    'tw:[&_button[aria-pressed=true]]:text-[#246e67] tw:[&_button[aria-pressed=true]]:bg-[#e4eee8] tw:[&_button[aria-pressed=true]]:border-[#c8dbd1]',
  ].join(' '),
  'sonar-layout': [
    'tw:grid tw:[grid-template-columns:minmax(0,_1fr)_clamp(280px,_23vw,_380px)] tw:items-start tw:gap-6',
    'tw:[@media(max-width:_800px)]:[grid-template-columns:minmax(0,_1fr)] tw:[@media(max-width:_800px)]:gap-4',
  ].join(' '),
  'sonar-board-panel': [
    'tw:border tw:border-solid tw:border-line tw:bg-surface tw:rounded-[18px] tw:min-w-0 tw:overflow-hidden',
  ].join(' '),
  'sonar-instrument-panel': [
    'tw:border tw:border-solid tw:border-line tw:bg-surface tw:rounded-[18px] tw:[padding:clamp(18px,_1.5vw,_26px)]',
    'tw:[&>button]:w-full',
    'tw:[@media(max-width:_800px)]:grid tw:[@media(min-width:_441px)_and_(max-width:_800px)]:[grid-template-columns:minmax(0,_1fr)_auto] tw:[@media(max-width:_800px)]:gap-3 tw:[@media(max-width:_800px)]:items-center',
    'tw:[@media(max-width:_800px)]:[&>button]:text-[12px]',
    'tw:[@media(max-width:_440px)]:[grid-template-columns:minmax(0,_1fr)]',
  ].join(' '),
  'sonar-log-panel': [
    'tw:border tw:border-solid tw:border-line tw:bg-surface tw:rounded-[18px] tw:[padding:clamp(18px,_1.5vw,_26px)]',
    'tw:[&_h2]:text-[16px] tw:[&_h2]:[margin:0_0_16px]',
  ].join(' '),
  'sonar-board-heading': [
    'tw:flex tw:items-center tw:justify-between tw:[padding:12px_20px] tw:[font:12px_var(--mono)] tw:text-muted',
  ].join(' '),
  'sonar-sidebar': [
    'tw:grid tw:gap-4',
    'tw:[@media(max-width:_800px)]:[grid-template-columns:minmax(0,_1fr)]',
  ].join(' '),
  'sonar-dial': [
    'tw:flex tw:[justify-content:center] tw:[padding:10px_0_18px] tw:text-[var(--sonar-accent)]',
    'tw:[&_.icon]:[width:clamp(56px,_5vw,_88px)] tw:[&_.icon]:h-auto tw:[&_.icon]:[opacity:0.75]',
    'tw:[@media(max-width:_800px)]:hidden',
  ].join(' '),
  'sonar-counters': [
    'tw:grid tw:gap-3',
    'tw:[&>div]:flex tw:[&>div]:justify-between tw:[&>div]:gap-3 tw:[&>div]:items-center',
    'tw:[&_span]:text-muted tw:[&_span]:text-[clamp(12px,_0.9vw,_15px)]',
    'tw:[&_strong]:[font:500_clamp(18px,_1.5vw,_26px)_var(--mono)] tw:[&_strong]:whitespace-nowrap',
    'tw:[@media(max-width:_800px)]:gap-2',
    'tw:[&_progress]:min-w-0 tw:[&_progress]:w-20 tw:[&_progress]:h-1.5 tw:[&_progress]:[accent-color:var(--sonar-accent)]',
  ].join(' '),
  'sonar-status': [
    'tw:[min-height:2.6em] tw:text-[13px] tw:[line-height:1.6] tw:text-[var(--sonar-accent)] tw:[margin:18px_0]',
    'tw:[@media(max-width:_800px)]:m-0 tw:[@media(max-width:_800px)]:[grid-column:1_/_-1] tw:[@media(max-width:_800px)]:[grid-row:2] tw:[@media(max-width:_800px)]:[min-height:1.6em]',
  ].join(' '),
  'sonar-log': ['tw:grid tw:gap-2 tw:max-h-90 tw:[overflow:auto]'].join(' '),
  'sonar-reading': [
    'tw:w-full tw:min-h-17 tw:flex tw:items-center tw:gap-3 tw:p-3 tw:text-left tw:bg-[#f6f6f1] tw:border tw:border-solid tw:border-transparent tw:[border-radius:11px]',
    'tw:[&[aria-pressed=true]]:border-[var(--echo-color)] tw:[&[aria-pressed=true]]:bg-[var(--echo-fill)]',
    'tw:[&>span:nth-child(2)]:grid tw:[&>span:nth-child(2)]:[gap:5px]',
    'tw:[&_strong]:[font:500_22px_var(--mono)]',
    'tw:[&_small]:[font:11px_var(--sans)] tw:[&_small]:text-muted',
    'tw:[&>.icon]:ml-auto tw:[&>.icon]:w-4.5 tw:[&>.icon]:text-[var(--echo-color)] tw:[&>.icon]:invisible',
    'tw:[&[aria-pressed=true]>.icon]:visible',
  ].join(' '),
  'sonar-badge': [
    'tw:[display:inline-grid] tw:[place-items:center] tw:shrink-0 tw:w-6.5 tw:h-6.5 tw:[border-radius:50%] tw:bg-[var(--echo-color,_#237a77)] tw:text-[#fff] tw:[font:500_12px_var(--mono)]',
  ].join(' '),
  'sonar-comparison': [
    'tw:mt-5 tw:pt-3.5 tw:[border-top:1px_solid_var(--line)]',
    'tw:[&_h3]:text-[13px] tw:[&_h3]:font-medium tw:[&_h3]:[margin:0_0_14px]',
    'tw:[&_p]:text-muted tw:[&_p]:text-[13px] tw:[&_p]:[line-height:1.7]',
    'tw:[&_small]:block tw:[&_small]:text-muted tw:[&_small]:text-[11px] tw:[&_small]:[line-height:1.7]',
  ].join(' '),
  'sonar-empty': ['tw:text-muted tw:text-[13px] tw:[line-height:1.7]'].join(' '),
  'sonar-equation': ['tw:flex tw:items-center tw:gap-3 tw:[font:20px_var(--mono)]'].join(' '),
  'sonar-pause': [
    'tw:absolute tw:[inset:0] tw:grid tw:[place-content:center] tw:text-center tw:bg-[#f8f8f1f5]',
    'tw:[&[hidden]]:hidden',
  ].join(' '),
  'sonar-storage': ['tw:[&:empty]:hidden', 'tw:text-[#996223] tw:text-[13px]'].join(' '),
  'sonar-dialog': [
    'tw:[width:min(650px,_calc(100vw_-_28px))] tw:[overscroll-behavior:contain]',
    'tw:[&_h2:focus]:[outline:none]',
  ].join(' '),
  'sonar-dialog-content': [
    'tw:[&>p]:text-muted tw:[&>p]:text-[14px] tw:[&>p]:[line-height:1.8]',
  ].join(' '),
  'sonar-help-steps': [
    'tw:grid tw:gap-5 tw:[margin:20px_0_28px]',
    'tw:[&_section]:flex tw:[&_section]:gap-3.5',
    'tw:[&_h3]:text-[15px] tw:[&_h3]:[margin:2px_0_8px]',
    'tw:[&_p]:text-[13px] tw:[&_p]:[line-height:1.8] tw:[&_p]:text-muted tw:[&_p]:m-0',
  ].join(' '),
  'sonar-help-example': [
    'tw:relative tw:h-34.5 tw:[margin:20px_0] tw:bg-[#f3f5ef] tw:rounded-xl',
    'tw:[&_span]:absolute tw:[&_span]:top-3.5 tw:[&_span]:w-22.5 tw:[&_span]:h-19.5 tw:[&_span]:grid tw:[&_span]:[place-items:start] tw:[&_span]:p-2 tw:[&_span]:[border:2px_solid] tw:[&_span]:[border-radius:6px] tw:[&_span]:[font:14px_var(--mono)]',
    'tw:[&_strong]:absolute tw:[&_strong]:bottom-3.5 tw:[&_strong]:w-full tw:[&_strong]:text-center tw:[&_strong]:[font:14px_var(--mono)]',
  ].join(' '),
  'sonar-example-a': ['tw:[left:calc(50%_-_65px)] tw:text-[#237a77] tw:bg-[#237a7712]'].join(' '),
  'sonar-example-b': ['tw:[left:calc(50%_-_25px)] tw:text-[#a2692a] tw:bg-[#c1842b12]'].join(' '),
  'sonar-records': [
    'tw:p-0 tw:[list-style-position:inside] tw:[margin:24px_0]',
    'tw:[&_li]:flex tw:[&_li]:justify-between tw:[&_li]:gap-3 tw:[&_li]:[padding:14px_0] tw:[&_li]:[border-bottom:1px_solid_var(--line)] tw:[&_li]:text-[12px]',
    'tw:[&_strong]:[font:15px_var(--mono)]',
  ].join(' '),
  'sonar-mobile-records': ['tw:hidden', 'tw:[@media(max-width:_800px)]:[display:inline-flex]'].join(
    ' ',
  ),
}
